'use strict';

const $ = id => document.getElementById(id);
const state = { account: null, peer: null, call: null, pending: null, stream: null, muted: false, active: 'home', chat: null, friends: [], dmTimer: null, centralTimer: null, callTimer: null, centralMessages: [] };
const key = 'linkup.discord.account';
const friendsKey = 'linkup.discord.friends';
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const load = (name, fallback) => { try { return JSON.parse(localStorage.getItem(name)) ?? fallback; } catch { return fallback; } };
const save = (name, value) => localStorage.setItem(name, JSON.stringify(value));
state.account = load(key, null);
state.friends = load(friendsKey, []);

function toast(message) { const el = $('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => el.classList.remove('show'), 2800); }
function letter(name) { return (name || '?').trim().charAt(0).toUpperCase() || '?'; }
function friendlyId(name) { return `${name.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 10) || 'user'}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(0, 6)}`; }
function api(path, options = {}) { return fetch(`/api/v1${path}`, { headers: { 'content-type': 'application/json', ...options.headers }, ...options }).then(async r => { const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || 'Unable to reach chat service'); return data; }); }
function setConnection(online) { $('connection-state').className = `status ${online ? 'online' : ''}`; $('connection-state').innerHTML = `<i></i> ${online ? 'Voice ready' : 'Reconnecting'}`; }
function setAccountUI() { const a = state.account; $('account-avatar').textContent = letter(a.name); $('account-name').textContent = a.name; $('account-id').textContent = a.id; $('my-peer-id').textContent = a.id; $('settings-id').textContent = a.id; }
function renderFriends() { const list = $('friend-list'); $('friend-count').textContent = `${state.friends.length} friend${state.friends.length === 1 ? '' : 's'}`; $('dm-list').innerHTML = state.friends.map(friend => `<button class="dm-item ${state.chat?.id === friend.id ? 'active' : ''}" data-dm="${escapeHtml(friend.id)}"><span class="avatar small">${escapeHtml(letter(friend.name))}</span><span>${escapeHtml(friend.name)}</span></button>`).join(''); list.innerHTML = state.friends.length ? state.friends.map(friend => `<article class="friend-row"><span class="avatar">${escapeHtml(letter(friend.name))}</span><div><strong>${escapeHtml(friend.name)}</strong><small>${escapeHtml(friend.id)}</small></div><button data-message="${escapeHtml(friend.id)}">Message</button><button class="call-friend" data-call="${escapeHtml(friend.id)}">Call</button></article>`).join('') : '<p class="empty">No friends yet. Add a Call ID above to begin.</p>'; }
function addFriend(id, name = id) { if (!id || id === state.account.id) return false; const existing = state.friends.find(friend => friend.id === id); if (existing) { if (name && name !== id) existing.name = name; } else state.friends.unshift({ id, name }); save(friendsKey, state.friends); renderFriends(); return true; }
function showView(view) { state.active = view; document.querySelectorAll('.view').forEach(el => el.classList.remove('active')); document.querySelectorAll('[data-view]').forEach(el => el.classList.toggle('active', el.dataset.view === view)); const target = view === 'home' ? 'view-home' : view === 'settings' ? 'view-settings' : 'view-chat'; $(target).classList.add('active'); $('channel-icon').textContent = view === 'central' ? '#' : view === 'settings' ? '⚙' : state.chat ? '@' : '⌂'; $('channel-name').textContent = view === 'central' ? 'central' : view === 'settings' ? 'Settings' : state.chat?.name || 'Friends'; $('channel-topic').textContent = view === 'central' ? 'The place to talk with everyone.' : view === 'settings' ? 'Personal preferences' : state.chat ? `Direct messages with ${state.chat.name}` : 'Call or message people you know.'; if (view === 'central') { $('central-unread').hidden = true; loadCentral(); } }
async function openChat(friend) { state.chat = friend; showView('chat'); $('message-input').placeholder = `Message @${friend.name}`; renderFriends(); await loadDm(); }
function renderMessages(messages) { const target = $('message-list'); target.innerHTML = messages.length ? messages.map(message => `<article class="message"><span class="avatar">${escapeHtml(letter(message.author?.name || '?'))}</span><div class="message-body"><div class="message-meta"><strong>${escapeHtml(message.author?.name || 'Unknown')}</strong><small>${new Date(message.createdAt).toLocaleString([], { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</small></div><div class="message-text">${escapeHtml(message.text)}</div></div></article>`).join('') : '<p class="empty">No messages yet. Say hello!</p>'; target.scrollTop = target.scrollHeight; }
async function loadDm() { if (!state.chat) return; try { const data = await api(`/dms/${encodeURIComponent(state.chat.id)}?user=${encodeURIComponent(state.account.id)}`); renderMessages(data.messages); } catch (error) { renderMessages([]); toast('Chat service is unavailable.'); } }
async function loadCentral() { try { const data = await api('/channels/central/messages'); state.centralMessages = data.messages; renderMessages(data.messages); } catch (error) { renderMessages([]); toast('Chat service is unavailable.'); } }
async function sendMessage(event) { event.preventDefault(); const input = $('message-input'); const text = input.value.trim(); if (!text) return; const central = state.active === 'central'; if (!central && !state.chat) return; input.disabled = true; try { const path = central ? '/channels/central/messages' : `/dms/${encodeURIComponent(state.chat.id)}`; const data = await api(path, { method: 'POST', body: JSON.stringify({ text, author: state.account }) }); input.value = ''; if (central) { state.centralMessages.push(data.message); renderMessages(state.centralMessages); } else await loadDm(); } catch (error) { toast(error.message); } finally { input.disabled = false; input.focus(); } }
function initPeer(id) { state.peer = new Peer(id, { debug: 0, config: { iceServers: [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'stun:stun1.l.google.com:19302' }, { urls: 'stun:global.stun.twilio.com:3478' }] } }); state.peer.on('open', actualId => { state.account.id = actualId; save(key, state.account); setAccountUI(); setConnection(true); }); state.peer.on('error', error => { setConnection(false); if (error.type === 'unavailable-id') { state.account.id = friendlyId(state.account.name); save(key, state.account); state.peer.destroy(); initPeer(state.account.id); } else toast(`Voice connection: ${error.message}`); }); state.peer.on('call', receiveCall); }
async function captureAudio() { return navigator.mediaDevices.getUserMedia({ audio: { channelCount: { ideal: 1 }, echoCancellation: { ideal: true }, noiseSuppression: { ideal: true }, autoGainControl: { ideal: true }, sampleRate: { ideal: 48000 } }, video: false }); }
async function startCall(id, name = id) { if (!state.peer?.open) return toast('Voice service is still connecting.'); if (id === state.account.id) return toast("You can't call yourself."); try { state.stream = await captureAudio(); state.call = state.peer.call(id, state.stream, { metadata: { name: state.account.name, id: state.account.id } }); if (!state.call) throw new Error('Call could not start'); wireCall(state.call, name); showCall(name, 'Calling…'); } catch (error) { toast(error.name === 'NotAllowedError' ? 'Allow microphone access to call.' : error.message); cleanupCall(); } }
function receiveCall(call) { if (state.call || state.pending) { call.close(); return; } state.pending = call; const name = call.metadata?.name || call.peer; $('incoming-name').textContent = name; $('incoming-avatar').textContent = letter(name); $('incoming-modal').hidden = false; }
async function acceptCall() { if (!state.pending) return; try { state.stream = await captureAudio(); state.call = state.pending; state.pending = null; state.call.answer(state.stream); wireCall(state.call, state.call.metadata?.name || state.call.peer); $('incoming-modal').hidden = true; showCall(state.call.metadata?.name || state.call.peer, 'Connecting…'); } catch (error) { toast('Microphone access is required to accept.'); state.pending?.close(); state.pending = null; } }
function wireCall(call, name) { call.on('stream', stream => { $('remote-audio').srcObject = stream; $('call-state').textContent = 'Connected'; clearInterval(state.callTimer); const started = Date.now(); state.callTimer = setInterval(() => { const s = Math.floor((Date.now() - started) / 1000); $('call-timer').textContent = `${String(Math.floor(s / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`; }, 1000); }); call.on('close', cleanupCall); call.on('error', () => { toast('Call ended unexpectedly.'); cleanupCall(); }); }
function showCall(name, label) { $('call-name').textContent = name; $('call-avatar').textContent = letter(name); $('call-state').textContent = label; $('call-timer').textContent = '00:00'; $('call-modal').hidden = false; }
function cleanupCall() { state.stream?.getTracks().forEach(track => track.stop()); state.stream = null; state.call = null; state.muted = false; clearInterval(state.callTimer); $('call-modal').hidden = true; $('remote-audio').srcObject = null; }
async function setNotifications() { const enabled = $('notification-toggle').classList.contains('on'); if (enabled) { $('notification-toggle').classList.remove('on'); $('notification-toggle').setAttribute('aria-pressed', 'false'); localStorage.setItem('linkup.notifications', 'false'); return; } if (!('serviceWorker' in navigator) || !('PushManager' in window)) return toast('Notifications are not supported in this browser.'); const permission = await Notification.requestPermission(); if (permission !== 'granted') return toast('Notification permission was not granted.'); const registration = await navigator.serviceWorker.ready; try { const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: urlBase64ToUint8Array('BKJbUuhte1lxZc5iD85E3LHkHmIv1DLFBYCFz2sqZrlmNfZmkAIq9ktqSwlsOWVI-nQSCgopCkxKQTwi0PQ0uH0') }); await api('/notifications/subscriptions', { method: 'POST', body: JSON.stringify({ accountId: state.account.id, subscription }) }); $('notification-toggle').classList.add('on'); $('notification-toggle').setAttribute('aria-pressed', 'true'); localStorage.setItem('linkup.notifications', 'true'); toast('Notifications are on.'); } catch (error) { toast('Could not enable notifications.'); } }
function urlBase64ToUint8Array(value) { const padding = '='.repeat((4 - value.length % 4) % 4); const binary = atob((value + padding).replace(/-/g, '+').replace(/_/g, '/')); return Uint8Array.from(binary, char => char.charCodeAt(0)); }
function startPolling() { clearInterval(state.dmTimer); clearInterval(state.centralTimer); state.dmTimer = setInterval(() => { if (state.active === 'chat' && state.chat) loadDm(); }, 5000); state.centralTimer = setInterval(async () => { try { const data = await api('/channels/central/messages'); if (state.active !== 'central' && data.messages.length > state.centralMessages.length) $('central-unread').hidden = false; state.centralMessages = data.messages; if (state.active === 'central') renderMessages(data.messages); } catch {} }, 8000); }
function start() { const name = $('name-input').value.trim(); if (!name) return toast('Enter a display name first.'); state.account = state.account || { id: friendlyId(name), name }; state.account.name = name; save(key, state.account); $('join').hidden = true; $('app').hidden = false; setAccountUI(); initPeer(state.account.id); if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {}); const on = localStorage.getItem('linkup.notifications') === 'true'; $('notification-toggle').classList.toggle('on', on); $('notification-toggle').setAttribute('aria-pressed', String(on)); renderFriends(); showView('home'); startPolling(); }
$('start-button').addEventListener('click', start); $('name-input').addEventListener('keydown', event => { if (event.key === 'Enter') start(); }); $('add-friend').addEventListener('click', () => { const id = $('friend-id').value.trim(); if (!id) return toast('Paste a Call ID first.'); if (addFriend(id)) toast('Friend added.'); $('friend-id').value = ''; }); $('new-dm').addEventListener('click', () => $('friend-id').focus()); $('call-button').addEventListener('click', () => startCall($('callee-id').value.trim())); $('friend-list').addEventListener('click', event => { const id = event.target.dataset.call || event.target.dataset.message; if (!id) return; const friend = state.friends.find(item => item.id === id); if (event.target.dataset.call) startCall(id, friend?.name); else openChat(friend); }); $('dm-list').addEventListener('click', event => { const id = event.target.closest('[data-dm]')?.dataset.dm; if (id) openChat(state.friends.find(item => item.id === id)); }); document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => showView(button.dataset.view))); $('message-form').addEventListener('submit', sendMessage); $('copy-id').addEventListener('click', () => navigator.clipboard.writeText(state.account.id).then(() => toast('Call ID copied.'))); $('settings-copy').addEventListener('click', () => navigator.clipboard.writeText(state.account.id).then(() => toast('Call ID copied.'))); $('notification-toggle').addEventListener('click', setNotifications); $('mute-button').addEventListener('click', () => { state.muted = !state.muted; state.stream?.getAudioTracks().forEach(track => track.enabled = !state.muted); $('mute-button').textContent = state.muted ? '🔇' : '🎙'; }); $('hangup-button').addEventListener('click', () => { state.call?.close(); cleanupCall(); }); $('decline-button').addEventListener('click', () => { state.pending?.close(); state.pending = null; $('incoming-modal').hidden = true; }); $('accept-button').addEventListener('click', acceptCall); if (state.account?.name) { $('name-input').value = state.account.name; }
